[project]
name = "gemini-embed-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=0.4.0",
    "google-genai>=0.1.0",
    "numpy>=1.24.0",
    "python-dotenv>=1.0.0",
]
